#!/usr/bin/env python3
"""Merge translated JSONL files into satellite resx files.
Uses System.Resources.ResourceWriter (via Python xml + re) to ensure UTF-8 BOM + correct encoding.
Reads each trans_<lang>.jsonl, parses it, inserts <data> entries into Strings.<lang>.resx,
and writes the file with utf-8-sig BOM.

The ResGen on Windows pt-BR reads .resx as cp1252 even with BOM, so the actual .resources
binary is generated by the ResGenFix target (tools/ResGenFix/). This script only writes the resx XML.
"""

import json
import os
import re
import sys

LANGUAGES = ['es', 'fr', 'de', 'it', 'ja', 'ko', 'zh']
LANG_NAMES = {
    'es': 'Español', 'fr': 'Français', 'de': 'Deutsch',
    'it': 'Italiano', 'ja': '日本語', 'ko': '한국어', 'zh': '中文'
}
REPO = r'C:\Users\wande\Documents\ffx-editor-main'
RESX_DIR = os.path.join(REPO, 'FFXProjectEditor', 'Resources')


def read_jsonl(path):
    """Read JSONL file, return dict of key -> value."""
    result = {}
    with open(path, 'r', encoding='utf-8') as f:
        for i, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
                if 'key' in obj and 'value' in obj:
                    result[obj['key']] = obj['value']
                else:
                    print(f'  WARN: line {i} missing key/value: {line[:80]}')
            except json.JSONDecodeError as e:
                print(f'  WARN: line {i} bad JSON: {e} -> {line[:80]}')
    return result


def read_existing_keys(resx_path):
    """Read existing keys from resx."""
    with open(resx_path, 'r', encoding='utf-8-sig') as f:
        text = f.read()
    keys = re.findall(r'<data name="([^"]+)"', text)
    return set(keys)


def esc_xml(s):
    """Escape string for XML attribute/value."""
    return s.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('"', '&quot;')


def merge_into_resx(resx_path, translations):
    """Insert translations into resx, skipping existing keys."""
    with open(resx_path, 'r', encoding='utf-8-sig') as f:
        text = f.read()

    existing = set(re.findall(r'<data name="([^"]+)"', text))
    added = 0
    skipped = 0

    for key, value in translations.items():
        if key in existing:
            skipped += 1
            continue
        # Build data element
        data_element = f'  <data name="{key}" xml:space="preserve"><value>{esc_xml(value)}</value></data>\n'

        # Insert before </root>
        root_close = text.rfind('</root>')
        text = text[:root_close] + data_element + text[root_close:]
        added += 1

    # Write with BOM
    with open(resx_path, 'w', encoding='utf-8-sig', newline='') as f:
        f.write(text)

    return added, skipped


def main():
    for lang in LANGUAGES:
        jsonl_path = os.path.join(REPO, 'work', f'trans_{lang}.jsonl')
        resx_path = os.path.join(RESX_DIR, f'Strings.{lang}.resx')

        if not os.path.exists(jsonl_path):
            print(f'SKIP {lang}: {jsonl_path} not found')
            continue
        if not os.path.exists(resx_path):
            print(f'SKIP {lang}: {resx_path} not found')
            continue

        print(f'\n--- {LANG_NAMES.get(lang, lang)} ({lang}) ---')
        translations = read_jsonl(jsonl_path)
        existing_before = read_existing_keys(resx_path)
        added, skipped = merge_into_resx(resx_path, translations)
        existing_after = read_existing_keys(resx_path)

        # Verify
        en_path = os.path.join(RESX_DIR, 'Strings.resx')
        with open(en_path, 'r', encoding='utf-8-sig') as f:
            en_text = f.read()
        en_keys = set(re.findall(r'<data name="([^"]+)"', en_text))
        still_missing = en_keys - existing_after

        print(f'  Translations in JSONL: {len(translations)}')
        print(f'  Added to resx: {added}')
        print(f'  Skipped (already existed): {skipped}')
        print(f'  Total in resx now: {len(existing_after)}')
        print(f'  EN total: {len(en_keys)}')
        print(f'  Still missing from satellite: {len(still_missing)}')
        if still_missing:
            print(f'  Sample missing: {list(sorted(still_missing))[:5]}')

    print('\nDone. Run build + StringsIntegrityTests to validate.')


if __name__ == '__main__':
    main()
