<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>MapoutVpaFull</AssemblyName>
    <RootNamespace>MapoutVpaFull</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="/home/wanderson/Documents/ffx-editor-main/research_tools/BattleMap/MapoutVpa_EncounterZones_Full.cs" />
  </ItemGroup>
</Project>
