# edits_r2.py — final prototype edit table for [type-lift-r2] lane.
# Every entry: (addr, new_signature, evidence_comment)
# Evidence categories:
#   A = arg pushed to FFX_Battle_AccessCurrentActorData (0x794030) => actor INDEX
#   B = arg directly dereferenced with +0xF90-struct offsets AND callers pass
#       dispatcher return values => FFXBattleActorData *
#   C = arg is bitmask/blob-ptr/out-ptr/other (frame + disasm)
#   R = return type from tail (eax/movzx/fld/lea/xor eax)

EDITS = [
# ---------------- tier 1: stale FFXBattleActorRecord protos ----------------
("0x7825a0","void __cdecl(void)","no stack args; loops actor slots internally"),
("0x783a60","void __cdecl(int actorIndex)","arg0 u8 -> pushed to dispatcher 0x794030"),
("0x783c40","void __cdecl(int actorIndex)","arg0 u8 -> dispatcher"),
("0x783c70","void __cdecl(int actorIndex, int n2)","arg0 u8 -> dispatcher"),
("0x7840b0","void __cdecl(int actorIndex)","arg n18 -> dispatcher"),
("0x7842d0","FFXBattleActorData *__cdecl(void)","no args; returns dispatcher actor ptr"),
("0x7843a0","int __cdecl(void)","no args; counts actors, returns int"),
("0x7844d0","void __cdecl(void)","no args; loops slots"),
("0x7847d0","void __cdecl(int actorIndex)","arg0 u8 -> dispatcher; esi=dispatcher ret used at +0x606/+0x5D0/+0x5D4"),
("0x786080","void __cdecl(void)","no args; syncs party stats loop"),
("0x7872f0","void __cdecl(int actorIndex, void *buffer)","arg0 -> dispatcher; arg_4 = out buffer"),
("0x787490","void __cdecl(int actorIndex, void *buffer)","arg0 -> dispatcher; arg_4 = in buffer"),
("0x787900","void __cdecl(int actorIndex)","arg0 u8 -> dispatcher"),
("0x787960","void __cdecl(int actorIndex)","arg0 u8 -> dispatcher"),
("0x7879c0","int __cdecl(int mask)","arg0 = actor bitmask (AND/compared), returns int mask"),
("0x787a10","void __cdecl(int actorIndex, int action)","arg0 -> dispatcher; arg4 = menu/action mode"),
("0x787cd0","int __cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns flag int"),
("0x7884b0","void __cdecl(int actorIndex)","arg0 u8 -> dispatcher"),
("0x7884f0","void __cdecl(int actorIndex, int priority)","arg0 u8 -> dispatcher; arg4 value -> [actor+0x402] via cx"),
("0x788bf0","void __cdecl(int i)","arg0 = actor index -> dispatcher"),
("0x788c30","void __cdecl(int flags, int actorIndex)","arg4 (n18) -> dispatcher"),
("0x788ed0","int __cdecl(int i)","arg0 = actor index; returns [actor+0x6D1]"),
("0x7893a0","int __cdecl(unsigned __int8 *src, int arg_4)","arg0 = blob ptr; byte [src] = actor index -> dispatcher"),
("0x789670","int __cdecl(unsigned __int8 *src)","arg0 = blob ptr (reads +8/+0x24); returns int"),
("0x789990","int __cdecl(unsigned __int8 *dst_, int *arg_4, int n3, unsigned __int8 *arg_C, int *arg_10)","arg0 = dst blob; [dst_] = actor index -> dispatcher; attacker = dispatcher ret"),
("0x78abe0","int __cdecl(unsigned __int8 *src, int arg_4)","arg0 = blob ptr; [src] = actor index -> dispatcher"),
("0x78ace0","void __cdecl(FFXBattleActorData *actor)","REAL actor ptr: esi=[arg0]; direct derefs +0x12/+0x14(actorIndex)/+0xDCE; callers push dispatcher ret (0x7AA196, 0x7A90F1)"),
("0x78cda0","int __cdecl(int i)","arg0 = actor index -> dispatcher; returns flag"),
("0x78dcf0","void __cdecl(int actorIndex, int arg_4)","arg0 (n15) -> dispatcher"),
("0x78eed0","int __cdecl(int n3, int arg_4, int i)","arg8 (i) = actor index -> dispatcher"),
("0x78ef40","int __cdecl(int j, int n8)","n8 -> IsAeonMenuSlot; resolved esi index -> dispatcher; returns slot"),
("0x78f980","int __cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns status word"),
("0x78f9a0","int __cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns overdrive gauge"),
("0x78fa30","FFXBattleActorData *__cdecl(void)","no args; scans slots, returns actor ptr or -1"),
("0x78fad0","void *__cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns ptr into actor"),
("0x78faf0","void *__cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns ptr into actor"),
("0x78fb10","int __cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns [actor+0x65A]"),
("0x78fb30","int __cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns [actor+0x64D]"),
("0x78fbd0","void *__cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns item data ptr"),
("0x791230","void __cdecl(void)","no args; turn init loop"),
("0x791680","int __cdecl(int arg_0)","arg0 = condition selector; returns 1 (or-mask write)"),
("0x792260","void __cdecl(void)","no args"),
("0x792ab0","void __cdecl(void)","no args"),
("0x7932c0","void __cdecl(int actorIndex)","arg0 = index -> dispatcher"),
("0x793340","void __cdecl(int actorIndex, int arg_4)","arg0 (modelId misnomer) = actor index -> dispatcher"),
("0x793420","void __cdecl(int i, int n7)","arg0 i = actor index"),
("0x793d00","void __cdecl(void)","no args; resets monster slots"),
("0x793dd0","void __cdecl(int bitmask)","arg0 = actor bitmask"),
("0x793f20","void __cdecl(int n8, int arg_4)","arg0 (n8) = actor index -> dispatcher"),
("0x794070","void __cdecl(int i, int arg_4, int arg_8, float arg_C, void *transformOut)","arg0 i = index; arg_10 pushed twice as out-transform ptr"),
("0x794250","int __cdecl(int actorIndex)","arg0 -> dispatcher; returns [actor+0x508]"),
("0x794290","int __cdecl(int actorIndex)","arg0 -> dispatcher; returns [actor+0x4FC]"),
("0x794340","int __cdecl(int slotIndex, FFX_TargetType targetType, int includeInactive, int includeFlagged)","arg0 -> dispatcher in loop; builds actor bitmask"),
("0x794840","void __cdecl(int i, float *posOut)","arg0 u8 -> dispatcher; arg_4 = 2-float pos out"),
("0x7949a0","float __cdecl(int actorIndex)","arg0 u8 -> dispatcher; fld [actor+0x534]"),
("0x794a40","void __cdecl(int i)","arg0 u8 -> dispatcher; writes transform to globals"),
("0x794a80","float __cdecl(int i)","arg0 u8 -> dispatcher; returns float via st0"),
("0x794ac0","void __cdecl(int i, float *posOut)","arg0 u8 -> dispatcher; arg_4 = pos out"),
("0x794b80","void __cdecl(int n20, int n18, float *accumOut)","arg0 = index-ish; arg_8 = out accum"),
("0x794c30","void __cdecl(int i, float *posOut)","arg0 u8 -> dispatcher; arg_4 = pos out"),
("0x795000","void __cdecl(int n0x1E, int *out1, int *out2)","arg0 u8 -> dispatcher; writes [actor+0xF54]/+0xF58 via out ptrs"),
("0x795790","int __cdecl(int n0x1F)","arg0 -> dispatcher; returns flag"),
("0x795930","void __cdecl(int n20, int *out1, int *out2)","writes [actor+0xF34]/+0xF38 via out ptrs"),
("0x795e80","void __cdecl(int actorIndex)","arg0 u8 -> dispatcher; retn no eax"),
("0x79a210","void __cdecl(int *arg_0)","arg0 = out ptr; writes [arg_0]=0x20 marker"),
("0x79ad40","int __cdecl(int n15, int n320)","arg0 n15 -> dispatcher; returns availability int"),
("0x79ade0","int __cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns [actor+0x5D0]"),
("0x79ae00","int __cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns [actor+0x594]"),
("0x79ae60","int __cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns [actor+0x5D4]"),
("0x79ae80","int __cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns [actor+0x598]"),
("0x79aee0","int __cdecl(int n12543)","arg0 -> dispatcher; returns [actor+0x590]"),
("0x79af70","int __cdecl(int n0x1F)","arg0 u8 -> dispatcher; returns [actor+0x590]"),
("0x79b500","void __cdecl(int arg_0, int actorIndex)","arg4 (m) -> dispatcher"),
("0x79c090","void __cdecl(int n15, int n320, int *p_i)","arg0 n15 -> dispatcher; p_i = out ptr"),
("0x79e7e0","int __cdecl(int i)","arg0 -> dispatcher; returns status-effect flags"),
("0x79f3a0","void __cdecl(void)","no args; UI overlay loop"),
("0x79fd40","FFXBattleActorData *__cdecl(int i, int v)","arg0 -> dispatcher; returns actor ptr (writes [actor+0x40F]=v)"),
("0x7a2de0","int __cdecl(int arg_0)","arg0 = VM ctx; index from Field self-actor getter -> dispatcher"),
("0x7a2e10","float __cdecl(int arg_0, int arg_4, int arg_8)","arg0 = VM ctx; returns float via st0"),
("0x7a35f0","void __cdecl(int arg_0, int arg_4, int arg_8)","arg0 = VM ctx"),
("0x7a3d20","int __cdecl(int arg_0)","arg0 = VM ctx; self actor index -> dispatcher; reads [actor+0xDC0]"),
("0x7a5eb0","int __cdecl(int arg_0)","arg0 = VM ctx; returns actor status byte"),
("0x7a6050","int __cdecl(int arg_0, int *arg_4)","arg_4 = ptr-to-index -> dispatcher"),
("0x7a6150","int __cdecl(int arg_0, int arg_4, int arg_8)","arg0 = VM ctx; returns status byte"),
("0x7a6750","int __cdecl(int arg_0)","arg0 = VM ctx; returns check int"),
("0x7a6b00","void __cdecl(int arg_0, int arg_4, int arg_8)","3 stack slots used as VM ctx+floats"),
("0x7a70e0","void __cdecl(int arg_0, int arg_4, int arg_8)","arg0 = VM ctx"),
("0x7a7150","void __cdecl(int arg_0)","arg0 = VM ctx"),
("0x7a7220","void __cdecl(int arg_0)","arg0 = VM ctx"),
("0x7a7280","int __cdecl(int arg_0)","arg0 = VM ctx; returns check int"),
("0x7a8570","void __cdecl(int arg_0, int arg_4, int arg_8)","arg0 = VM ctx"),
("0x7a8c00","int __cdecl(int ActorBitmask)","arg0 = actor bitmask scanned per-actor; returns flag"),
("0x7ac860","int __cdecl(int slotIndex, int arg_4, int n0x1F, int n8)","arg0 u8 slot; 4 stack args"),
("0x7afe10","void __cdecl(int actionId, FFXBattleActorData *actor, int n0x10)","arg1 = REAL actor ptr: esi=[arg1]; direct deref [esi+0xF5C]; caller pushes dispatcher ret"),
("0x7b1190","void __cdecl(void)","no args; loops global overdrive slots"),
("0x7b27c0","int __cdecl(int n3, FFXBattleActorData *actor, int n255)","caller pushes esi=actor at arg4 slot; callee reads n3/n255"),
("0x7b4b80","void __cdecl(FFX_TargetType targetType, int n84, int n0x1F, int n7)","4 stack args per frame; no dispatcher call"),
# ---------------- tier 2: other broken protos (phantom fastcall/thiscall, junk rets) ----------------
("0x7890f0","void __cdecl(int n31, FFXBattleActorData *actor)","caller pushes esi=actor at arg4 (p_modelHandle slot); void ret"),
("0x78e460","void __cdecl(int n3, FFXBattleActorData *actor)","caller pushes esi=actor at arg4 (ia slot); void ret"),
("0x78e4b0","int __cdecl(int n3, FFXBattleActorData *actor)","arg4 = actor ptr (callers push dispatcher ret); returns int"),
("0x78f050","int __cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns int (lea/add eax)"),
("0x78f750","int __cdecl(int actorIndex)","arg0 -> dispatcher; returns eax=esi int"),
("0x7929d0","int __cdecl(void *src, int n64, int arg_8, int n255)","src = ring-buffer ptr (0x1136A68), not actor; returns -1 int"),
("0x794d30","int __usercall@<eax>(double@<st0>, int actorIndex, float *pos)","arg0 u8 index -> dispatcher; arg4 = pos out; eax=-1/0, st0=height"),
("0x795100","double __cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns st0 (height scale)"),
("0x795650","int __cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns movsx [actor+0x420]"),
("0x795a30","double __cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns st0 ([actor+0x4E4]*[0x3A8])"),
("0x795b50","FFXBattleActorData *__cdecl(int slotType, int limit)","returns ebx = dispatcher actor ptr"),
("0x795bc0","FFXBattleActorData *__cdecl(int slotType, int flag)","maps slotType -> const index (0x1D/0x1E) -> dispatcher; returns actor ptr"),
("0x795c50","void __cdecl(void)","no args; init/clear loop"),
("0x78d5a0","void __cdecl(int n3)","loops all actors clearing [actor+0x606] zombie bits"),
("0x78dc30","void __cdecl(int slotMask, int n0x1F, int arg_8)","3 args; index derived -> dispatcher"),
("0x78df40","void __cdecl(int flags)","arg0 = flags passed to SetActorDeathFlags in slot loop"),
("0x78e160","void __cdecl(void)","no args; post-victory CTB init loop"),
("0x791820","void __cdecl(void)","no args; switch on g_BattleStateId"),
("0x793680","void __cdecl(int n255, int n590823)","2 args; returns via cookie-check retn (void)"),
("0x793f00","void __cdecl(void)","no args"),
("0x7990e0","void __cdecl(int n3, FFXBattleActorData *actor, unsigned __int16 *rewards, int arg_C, int arg_10)","caller pushes esi=actor at arg4; rewards = u16 table ptr"),
("0x799d60","int __cdecl(int actorIndex, FFXBattleActorData *actor, unsigned __int8 *p_n0x1F, unsigned int arg_C)","arg1 = actor ptr (caller pushes dispatcher ret); arg2 = u8 blob ptr"),
("0x79a090","int __cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns 0/1"),
("0x79a770","int __cdecl(int actorIndex, int n0x1F, int *out1, int *out2, int *out3)","arg0 = index byte -> dispatcher; 3 out ptrs"),
("0x79a930","int __cdecl(int actorIndex, int n0x1F, int *out1, int *out2, int *out3)","same shape as 0x79A770"),
("0x79aa60","int __cdecl(int actorIndex, int n0x1F, int *o1, int *o2, int *o3, int *o4, int *o5, int *o6)","8 args: index + n0x1F + 6 out ptrs"),
("0x79ad20","int __cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns [actor+0x65D]"),
("0x79ada0","int __cdecl(int actorIndex)","arg0 -> dispatcher; returns flag int"),
("0x79adc0","int __cdecl(int actorIndex)","arg0 -> dispatcher; returns flag int"),
("0x79ae20","int __cdecl(int actorIndex)","arg0 -> dispatcher; returns byte"),
("0x79ae40","int __cdecl(int actorIndex)","arg0 -> dispatcher; returns byte"),
("0x79aea0","int __cdecl(int actorIndex)","arg0 -> dispatcher; returns byte"),
("0x79af20","float *__cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns actor+0x540 (FloatArray336)"),
("0x79af50","int __cdecl(int actorIndex)","arg0 -> dispatcher; returns byte"),
("0x7a5bb0","int __cdecl(int arg_0, int *pActorIndex)","arg_4 = ptr-to-index ([eax] pushed -> dispatcher); returns sbb/and int"),
("0x7a8900","double __cdecl(FFXBattleActorData *actor)","REAL actor ptr: eax=[arg0]; [eax+0xC]=actorSlotIndex cmp 0x1D; [eax+0x14]=index->dispatcher; fld [eax+0x4D4]; st0 ret"),
("0x7a9170","int __cdecl(int arg_0, int arg_4, int *arg_8, float arg_C)","4 stack slots; returns 0/xor int"),
("0x7a9400","void __cdecl(int actorIndex, float *outPos)","arg0 (n0x1F) = index -> dispatcher; arg_4 = pos out"),
("0x7a9730","double __cdecl(int i, FFXBattleActorData *actor, __int64 *outPos, int arg_C, int *arg_10, int *arg_14)","arg1 = actor ptr (callers push esi=dispatcher ret); 9 fld ops, st0 ret"),
("0x7aa070","int __cdecl(int i, int arg_4, int arg_8, float *arg_C, float *arg_10)","5 args; returns eax=esi int"),
("0x7ab320","void __cdecl(int actorIndex)","arg0 -> dispatcher; writes [actor+0xDFB]"),
("0x7ab520","void __cdecl(int actorIndex)","arg0 u8 -> dispatcher; writes [actor+0xDFB]=0xF"),
("0x7ab540","void __cdecl(int actorIndex)","arg0 u8 -> dispatcher; writes [actor+0xDFB]=0"),
("0x7ab560","void __cdecl(int n0x1F, int arg_4, int arg_8, float arg_C, int arg_10, int arg_14, int n32, float arg_1C, float arg_20, float arg_24, float arg_28)","11 stack args; ebx/ecx were phantoms"),
("0x7ab770","int __cdecl(int i, FFXBattleActorData *actor)","arg1 = actor ptr (caller pushes dispatcher ret); or eax,-1 int ret"),
("0x7ac6a0","void __cdecl(void)","no args; copies all slots to temp"),
("0x7adf20","void __cdecl(void)","no args"),
("0x7aeed0","void __cdecl(void)","no args"),
("0x7b0d60","int __cdecl(int amount, FFX_OverdriveType odType, int n3, FFXBattleActorData *actor, int arg_10, int arg_14, int arg_18)","7 args; arg3 = actor ptr (caller pushes esi); returns eax=esi int"),
("0x7b0f90","int __cdecl(unsigned int flags, FFXBattleActorData *actorA, int n3, FFXBattleActorData *actorB)","arg1+arg3 = actor ptrs (callers push dispatcher rets); returns eax=edi int"),
("0x7b1b60","void __cdecl(int n2, unsigned __int8 *reelData, float arg_8, float arg_C)","arg1 = reel blob ptr; void ret"),
("0x7b1920","void *__cdecl(int actorIndex, int *arg_4, int arg_8, int *arg_C)","arg0 u8 -> dispatcher; returns ptr or 0"),
("0x7b7200","void *__cdecl(int actorIndex, int *arg_4)","arg0 -> dispatcher; returns eax=esi ptr"),
("0x7b7cf0","void __cdecl(int slotIndex)","arg0 &0xFF -> dispatcher; void ret"),
("0x7b7da0","void __cdecl(int actorIndex)","arg0 -> dispatcher; void ret"),
("0x7b6f30","void __cdecl(int arg_0, int *arg_4)","writes bitmask via arg_4 ptr; void ret"),
("0x7b0510","void __cdecl(void *ctx)","arg0 = ctx ptr; [ctx+0xC] byte = actor index -> dispatcher; writes [actor+0xDFD]"),
("0x7b09c0","void *__cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns pool-entry ptr (lea eax,[...112AC70])"),
("0x7b09f0","void *__cdecl(int actorIndex)","arg0 u8 -> dispatcher; returns pool-entry ptr or 0"),
("0x78f810","void *__cdecl(int n0x1F, int *arg_4)","arg0 -> dispatcher; returns computed ptr in eax"),
("0x788270","FFXBattleActorData *__cdecl(void)","no args; returns dispatcher actor ptr"),
("0x7956f0","int __cdecl(int actorIndex, float *posOut)","arg0 u8 -> dispatcher; arg4 = pos out"),
("0x795730","int __cdecl(int actorIndex, float *posOut)","arg0 u8 -> dispatcher; arg4 = pos out"),
("0x796160","int __cdecl(int actorIndex, float *pos)","arg0 -> dispatcher; arg4 = pos ptr"),
("0x7961e0","int __cdecl(int actorIndex, float *pos)","arg0 u8 -> dispatcher; arg4 = pos ptr"),
("0x796230","int __cdecl(int actorIndex, float *pos)","arg0 u8 -> dispatcher; arg4 = pos ptr"),
("0x7948f0","int __cdecl(int actorIndex, float *pos)","arg0 u8 -> dispatcher; arg4 = pos ptr"),
("0x79e050","void __cdecl(void *ctx)","arg0 = ctx/dword stored to local; loops all actors"),
("0x79d450","void __cdecl(void)","no args; camera animation switch"),
("0x7af930","void __cdecl(void)","no args; field pair positioning loop"),
("0x7d7310","void __cdecl(void)","no args; syncs all actor chr positions"),
("0x7854d0","int __cdecl(int n0x1E, FFX_BattleContext *battleContext, FFX_MenuFlags *flags)","3 args per frame; returns menu row mask int"),
("0x787bb0","void __cdecl(int n3)","arg0 = index -> IsValidBattleSlot + dispatcher; void ret"),
("0x7882c0","void __cdecl(int arg_0, int arg_4)","2 args; sets [actor+0xDFB]=5; void ret"),
("0x788f20","void __cdecl(int i)","arg0 = index; void ret"),
]
