struct FFXBattleActorData {
  int modelHandle;
  int fieldAttachId;
  int characterId;
  unsigned __int8 actorSlotIndex;
  char _pad0D;
  __int16 formId;
  char pad16[20];
  unsigned __int8 isReadyToSpawn;
  char pad37[971];
  unsigned __int8 pendingCommandId;
  char pad1009;
  __int16 actionTargetSlot;
  unsigned __int8 hasActiveAction;
  char pad1012;
  unsigned __int8 prevStateCache;
  unsigned __int8 sourceStateValue;
  char pad1015[44];
  unsigned __int8 currentMotionId;
  char pad1060[37];
  unsigned __int8 menuActionState;
  char pad1098[5];
  unsigned __int8 commandSubMode;
  unsigned __int8 actionLockedFlag;
  char pad1105[138];
  float maxHp;
  float maxMp;
  char pad1436[10];
  unsigned __int8 turnDamagePercent;
  char pad1467[7];
  unsigned __int8 commandStyle;
  unsigned __int8 commandStyleCounter;
  char pad1476[68];
  unsigned __int8 statusFlagA;
  unsigned __int8 statusFlagB;
  unsigned __int8 statusFlagC;
  char pad1547[50];
  unsigned __int8 overdriveActionState;
  unsigned __int8 overdriveLevel;
  char pad1600[28];
  unsigned __int8 preDeathStateCache;
  unsigned __int8 preDeathSourceValue;
  char _pad591[3];
  int maxHpStat;
  int maxMpStat;
  char _pad59C[3];
  unsigned __int8 reflectActiveFlag;
  char pad1739_pre[8];
  unsigned __int8 strength;
  unsigned __int8 defense;
  unsigned __int8 magic;
  unsigned __int8 magicDefense;
  unsigned __int8 agility;
  unsigned __int8 luck;
  unsigned __int8 evasion;
  unsigned __int8 accuracy;
  char pad5B0[12];
  int overdriveCharge;
  char _pad5C0[16];
  int currentHp;
  int currentMp;
  char _pad5D8[50];
  int currentAnimId;
  unsigned __int8 nulTideBlock;
  char pad60F;
  unsigned __int8 nulShockBlock;
  char pad611[2];
  unsigned __int8 nulHolyBlock;
  unsigned __int8 nulDarkBlock;
  char pad615[71];
  unsigned __int8 ctbFinalWaitValue;
  unsigned __int8 ctbWaitTimeBase;
  unsigned __int8 strChargeLevel;
  unsigned __int8 defChargeLevel;
  unsigned __int8 magChargeLevel;
  unsigned __int8 mdefChargeLevel;
  unsigned __int8 agiChargeLevel;
  unsigned __int8 luckChargeLevel;
  char pad664[88];
  unsigned __int8 ctbSkipDecrementFlag;
  char pad6BD;
  __int16 autoAbilities2;
  char pad6C0[2];
  __int16 statusBitfieldB;
  char pad6C4[32];
  int currentStrength;
  int currentMagic;
  int currentAgility;
  char pad6F0[4];
  int maxComputedStat;
  char pad6F8[52];
  int inlineActionId;
  char pad730[124];
  int overdriveGauge;
  unsigned __int8 pad7B0;
  unsigned __int8 damageFlag;
  char pad7B2[24];
  unsigned __int8 hasQueuedAction;
  unsigned __int8 subStateMode;
  char pad7CC[2];
  unsigned __int8 lastDamageSourceActorId;
  char pad7CF[2];
  unsigned __int8 actorTurnState;
  char pad7D2;
  unsigned __int8 turnSkipFlag;
  char pad7D4[5];
  unsigned __int8 postDamageFlag;
  char pad7DA[2];
  unsigned __int8 mainStateMode;
  char pad7DD[27];
  unsigned __int8 actionRingIndex;
  char pad7F9[326];
  unsigned __int8 statusBitfieldA;
  char pad940[1189];
  unsigned __int8 actionSlot;
  char padDE6[426];
};
