#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""classify_tierb.py v2 — mechanical content-shape classifier for the 1,331
tier-b-ambiguous units skipped across Y5 draft batches b01..b23.

Feature flags (non-exclusive) are computed per unit; a primary bucket is then
assigned by a deterministic decision list (first match wins). Claimable buckets
carry structurally usable technical content; the rest is editorial/scaffolding.

Decision order:
  1. doc-meta      — doc-header metadata lines (Date:/Lane:/Status:/Fonte:/...)
  2. hrule         — pure -, *, _, = rule lines
  3. bold-label    — only **...** label (opt. ':')
  4. struct-field  — Byte N:/bit N:/+N:/offset N/(type)/-- comment/Ident.Type (
  5. index-map     — line starts "N: Name" (ordinal/enum maps like "4: Tactician")
  6. enum-map      — >=2 "NAME = val" pairs (numeric or UPPER rhs)
  7. formula       — '=' with arithmetic/bit-shift, /256, x<<n
  8. code-assign   — single '=' assignment ("x = expr")
  9. cond-expr     — code comparison/logic ops (>=, <=, !=, ==, &&, ||)
 10. mapping-arrow — '->', '→', '↔', '=>' mappings
 11. asm-dump      — x86 mnemonic lines (push/cmp/mov/...) with code-ish operand
 12. asset-ref     — game-asset filename (name.dll/.bin/.txc/.fev/...)
 13. code-ident    — snake_case/camelCase identifiers mentioned in text
 14. doc-ref       — only doc/source filenames (.md/.ts/.cs/...) = cross-refs
 15. lead-in       — ends with ':' (intro line of a list/table)
 16. prose         — narrative remainder

Claimable = buckets 4..13. Residual editorial = doc-meta, hrule, bold-label,
doc-ref, lead-in, prose.
"""
import json
import re
from collections import Counter

TIERB = "/home/wanderson/Documents/ffx-editor-main/work/_y5_tierb/tierb_units.json"
OUT = "/home/wanderson/Documents/ffx-editor-main/work/_y5_tierb/tierb_classification.json"

DOC_META_RE = re.compile(
    r"^[\s>\-*#]*(?:\*\*)?\s*(date|data|lane|author|status|fontes?|escopo|sources?|"
    r"artefatos?|generated|research completed|base auditada|papel|generated by|"
    r"fim da|consolidates)\b",
    re.I)
HRULE_RE = re.compile(r"^[\s\-*_=·—]+$")
BOLD_ONLY_RE = re.compile(r"^(\*\*[^*]+\*\*\s*)+:?$")
BYTE_FIELD_RE = re.compile(r"\b[Bb]yte\s*\d+\s*[:=]|\b[Bb]ytes\s*\d+\s*[-–:]")
BIT_FIELD_RE = re.compile(r"\bbits?\s*\d+(?:\s*\.\.\s*\d+)?\s*[:=]", re.I)
INDEX_MAP_RE = re.compile(r"^\s*\d{1,4}\s*:\s+\S", re.M)
OFFS_FIELD_RE = re.compile(r"(?:^|[\s,])\+\s*\d+\s*[:=]|\boffset\s*\+?\d+|\boffs?\s*[:=]\s*\d+", re.I | re.M)
TYPE_TAG_RE = re.compile(
    r"\((?:u?int\d*|byte|word|dword|qword|short|ushort|long|float|double|"
    r"s8|s16|s32|u8|u16|u32|u64|char|bool|string|ptr|pointer)[^)]*\)", re.I)
BARE_TYPE_RE = re.compile(r"\b(u8|u16|u32|u64|s8|s16|s32|uint8|uint16|uint32|"
                          r"int16|int32|ushort|dword|qword|float32|VLQ|vlq)\b")
DASH_COMMENT_RE = re.compile(r"\s--\s|--\s*$")
DOC_EXTS = {"md", "ts", "cs", "py", "cpp", "h", "json", "txt", "log", "c", "cc", "js"}
DOTTED_PAREN_RE = re.compile(r"\b[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)+\s*\(")
ENUM_RUN_RE = re.compile(r"\b[A-Za-z_][A-Za-z0-9_]{1,}\s*=\s*"
                         r"(?:0x[0-9A-Fa-f]+|\d+|[A-Z_][A-Z0-9_]{1,})\b")
FORMULA_RE = re.compile(r"\bformula\b\s*[:=]|\w+\s*=\s*[\w.()]+\s*[-+*/×]|"
                        r"/\s*256\b|\*\s*256\b|<<\s*\d+|>>\s*\d+|\bmod\s+\d+", re.I)
ASSIGN_RE = re.compile(r"[A-Za-z_\)\]*]\s*=(?![=>])\s*[^=\s]")
CMP_OP_RE = re.compile(r">=|<=|!=|==|&&|\|\|")
ARROW_RE = re.compile(r"->|→|↔|=>|<=>")
ASM_MNEM = ("push|pop|mov|movzx|movsx|cmp|jmp|call|lea|xor|test|add|sub|inc|dec|"
            "ret|retn|nop|shl|shr|sar|and|or|imul|mul|idiv|div|jne|je|jz|jnz|jg|"
            "jge|jl|jle|ja|jb|jae|jbe|xchg|leave|int3|fld|fstp|fmul|fadd|cvtsi")
ASM_LINE_RE = re.compile(r"^\s*(" + ASM_MNEM + r")\b(.*)$", re.I | re.M)
ASM_OPERAND_OK = re.compile(r"[0-9A-Z_,;\[\]()*+]|$"
                            r"|\b(e?[abcd]x|e?[sd]i|e?[sb]p|[abcd][lh]|r\d+|xmm\d+|"
                            r"byte|word|dword|qword|ptr|short|near|far)\b", re.I)
ASSET_EXT_RE = re.compile(
    r"\b[\w][\w.\-]*\.(dll|bin|txc|clt|dds|phyre|fev|fsb|vpa|ath|atd|clp|dcp|fmt|"
    r"sps2|anm|an2|omd|psarc|vbf|yndt|bkm|tbl|dat|exe|i64|tm2|pbd|sgb|mdl|pss|"
    r"vag|irx|elf|ftc|ftcx|arc|ffb|kit|sga|xwb|xsb|ma2|rsd|ply|ccd)\b", re.I)
ANY_EXT_RE = re.compile(r"\b[\w][\w.\-]*\.(\w{1,6})\b")
SNAKE_IDENT_RE = re.compile(r"\b[A-Za-z]\w*_\w+\b")
CAMEL_IDENT_RE = re.compile(r"\b[a-z]{2,}[A-Z][A-Za-z0-9]*\b")


def is_asm(text: str) -> bool:
    for m in ASM_LINE_RE.finditer(text):
        rest = m.group(2).strip()
        if rest == "" or ASM_OPERAND_OK.search(rest):
            # operand must not be a plain lowercase english word start
            first = rest.split()[0] if rest else ""
            if first and first[0].islower() and not ASM_OPERAND_OK.search(first):
                continue
            return True
    return False


def features(text: str) -> dict:
    t = text.replace("\r", " ")
    flat = re.sub(r"\s+", " ", t).strip()
    enum_hits = len(ENUM_RUN_RE.findall(flat))
    dotted = False
    for m in DOTTED_PAREN_RE.finditer(flat):
        tail = m.group(0).rstrip(" (").rsplit(".", 1)[-1].lower()
        if tail not in DOC_EXTS:
            dotted = True
            break
    exts = {m.group(1).lower() for m in ANY_EXT_RE.finditer(flat)}
    # ident detection masks path tokens (a/b/c) and filename tokens (name.ext):
    # otherwise "research_tools/Ps2X.cs" and "docs/reverse/FFX_A_B.md" would
    # register as snake_case identifiers when they are really file references.
    masked = re.sub(r"\S*/\S*|\b\S+\.\w{1,6}\b", " ", flat)
    return {
        "doc_meta": bool(DOC_META_RE.match(flat)),
        "hrule": bool(HRULE_RE.fullmatch(flat)) and len(flat) >= 3,
        "bold_label": bool(BOLD_ONLY_RE.fullmatch(flat)),
        "byte_field": bool(BYTE_FIELD_RE.search(flat)),
        "bit_field": bool(BIT_FIELD_RE.search(t)),
        "index_map": bool(INDEX_MAP_RE.search(t)),
        "offset_field": bool(OFFS_FIELD_RE.search(t)),
        "type_tag": bool(TYPE_TAG_RE.search(flat)),
        "bare_type": bool(BARE_TYPE_RE.search(flat)),
        "dash_comment": bool(DASH_COMMENT_RE.search(flat)),
        "dotted_paren": dotted,
        "enum_pairs": enum_hits,
        "formula": bool(FORMULA_RE.search(flat)),
        "assign": bool(ASSIGN_RE.search(flat)),
        "cmp_op": bool(CMP_OP_RE.search(flat)),
        "arrow": bool(ARROW_RE.search(flat)),
        "asm": is_asm(t),
        "asset_ext": bool(ASSET_EXT_RE.search(flat)),
        "doc_ext_only": bool(exts) and exts <= DOC_EXTS,
        "snake_ident": bool(SNAKE_IDENT_RE.search(masked)),
        "camel_ident": bool(CAMEL_IDENT_RE.search(masked)),
        "lead_in": flat.endswith(":"),
        "len": len(flat),
    }


def primary_bucket(f: dict) -> str:
    if f["doc_meta"]:
        return "doc-meta"
    if f["hrule"]:
        return "hrule"
    if f["bold_label"]:
        return "bold-label"
    if (f["byte_field"] or f["bit_field"] or f["offset_field"] or f["type_tag"]
            or f["dash_comment"] or f["dotted_paren"] or f["bare_type"]):
        return "struct-field"
    if f["index_map"]:
        return "index-map"
    if f["enum_pairs"] >= 2:
        return "enum-map"
    if f["formula"]:
        return "formula"
    if f["assign"]:
        return "code-assign"
    if f["cmp_op"]:
        return "cond-expr"
    if f["arrow"]:
        return "mapping-arrow"
    if f["asm"]:
        return "asm-dump"
    if f["asset_ext"]:
        return "asset-ref"
    if f["snake_ident"] or f["camel_ident"]:
        return "code-ident"
    if f["doc_ext_only"]:
        return "doc-ref"
    if f["lead_in"]:
        return "lead-in"
    return "prose"


CLAIMABLE = {"struct-field", "index-map", "enum-map", "formula", "code-assign",
             "cond-expr", "mapping-arrow", "asm-dump", "asset-ref", "code-ident"}


def main():
    units = json.load(open(TIERB, encoding="utf-8"))
    out = []
    for u in units:
        f = features(u["text"])
        out.append({**u, "features": f, "bucket": primary_bucket(f),
                    "claimable": primary_bucket(f) in CLAIMABLE})
    json.dump(out, open(OUT, "w", encoding="utf-8"), ensure_ascii=False, indent=1)

    bc = Counter(o["bucket"] for o in out)
    nc = sum(1 for o in out if o["claimable"])
    print(f"total tier-b units: {len(out)}   claimable: {nc} ({100*nc/len(out):.1f}%)")
    for k, v in bc.most_common():
        tag = "CLAIMABLE" if k in CLAIMABLE else "residual "
        print(f"  [{tag}] {k:15s} {v:5d}  {100*v/len(out):5.1f}%")
    fc = Counter()
    for o in out:
        for k, v in o["features"].items():
            if v is True or (isinstance(v, int) and k == "enum_pairs" and v > 0):
                fc[k] += 1
    print("\nfeature flags (non-exclusive):")
    for k, v in fc.most_common():
        print(f"  {k:15s} {v:5d}")
    # per-batch claimable counts
    print("\nper-batch claimable/total:")
    by_b = Counter((o["batch"]) for o in out)
    by_bc = Counter((o["batch"]) for o in out if o["claimable"])
    for b, tot in by_b.most_common():
        print(f"  {b:32s} {by_bc[b]:4d}/{tot}")


if __name__ == "__main__":
    main()
