<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="/home/wanderson/Documents/ffx-editor-main/FFXProjectEditor/FfxLib/Save/FfxSaveCore.cs" />
    <Compile Include="/home/wanderson/Documents/ffx-editor-main/FFXProjectEditor/FfxLib/Save/FfxSaveFormat.cs" />
    <Compile Include="/home/wanderson/Documents/ffx-editor-main/FFXProjectEditor/FfxLib/Save/FfxSaveChecksum.cs" />
    <Compile Include="/home/wanderson/Documents/ffx-editor-main/FFXProjectEditor/FfxLib/Save/FfxSaveStringCodec.cs" />
    <Compile Include="/home/wanderson/Documents/ffx-editor-main/FFXProjectEditor/FfxLib/Save/FfxSaveMemoryCard.cs" />
    <Compile Include="/home/wanderson/Documents/ffx-editor-main/FFXProjectEditor/FfxLib/Save/FfxSaveFile.cs" />
  </ItemGroup>
</Project>
