<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>Ps2RsdPlyMa2Reader</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Ps2RsdModelReader.cs" />
    <Compile Include="Ps2PlyModelReader.cs" />
    <Compile Include="Ps2Ma2MaterialReader.cs" />
    <Compile Include="_rsd_ply_ma2_test.cs" />
  </ItemGroup>
</Project>
