#!/usr/bin/env python3
"""Confirmed mislabel rename plan — built from export asm evidence + xrefs.
Each entry: addr, expected old name (verify before rename), new name, evidence.
"""
import json, re

PLAN = [
 # === Phyre static-dtor block (was FFX_Sound_* by proximity sweep) ===
 ("0xafb0a0","FFX_Sound_FmodSfxPlayBattlePre","FFX_Phyre_ClassMemberDtor_C94220","mov ecx,byte_C94220; jmp PClassDataMember_Destructor; data-xref: Phyre_AssetType_Scripting_Register"),
 ("0xafb210","FFX_Sound_FmodSfxPlayFromBattle","FFX_Phyre_MemberArrayDtor_C94B9C","mov ecx,dword_C94B9C; jmp PClassDataMemberArray_VftableInit(array dtor); data-xref: Phyre_Matrix3_RegisterClassDescriptor"),
 ("0xafbae0","FFX_Sound_FmodMusicGetVolume","FFX_Phyre_StaticDtorNoOp_C9791C","mov ecx,unk_C9791C; jmp nullsub_217 (empty static dtor); data-xref: Phyre_PArray_PInt32_PUInt8_RegisterClassDescriptor"),
 ("0xafbb50","FFX_Sound_FmodMusicPlay","FFX_Phyre_StaticDtorNoOp_C97890","mov ecx,unk_C97890; jmp nullsub_217; data-xref: Phyre_PArray_bool_PUInt8_RegisterClassDescriptor"),
 ("0xafbc10","FFX_Sound_FmodMusicStop","FFX_Phyre_StaticDtorNoOp_C979E0","mov ecx,unk_C979E0; jmp nullsub_217; data-xref: Phyre_PArray_bool_PInt16_RegisterClassDescriptor"),
 ("0xafbd60","FFX_Sound_FmodMusicSwitchTrack","FFX_Phyre_StaticDtorNoOp_C97DB4","mov ecx,unk_C97DB4; jmp nullsub_217; data-xref: Phyre_PArray_PUInt128_PInt32_RegisterClassDescriptor"),
 ("0xafbe40","FFX_Sound_FmodMusicCrossfade","FFX_Phyre_StaticDtorNoOp_C97E94","mov ecx,unk_C97E94; jmp nullsub_217; data-xref: Phyre_PArray_PUInt64_PUInt32_RegisterClassDescriptor"),
 ("0xafbf50","FFX_Sound_FmodMusicGetFftSpectrum","FFX_Phyre_StaticDtorNoOp_C98380","mov ecx,unk_C98380; jmp nullsub_217; data-xref: Phyre_PArray_PUInt16_double_RegisterClassDescriptor"),
 ("0xafc190","FFX_Sound_FmodMusicGetTimeMs","FFX_Phyre_StaticDtorNoOp_C97F90","mov ecx,unk_C97F90; jmp nullsub_217; data-xref: Phyre_PArray_PUInt16_PUInt64_RegisterClassDescriptor"),
 ("0xafc210","FFX_Sound_FmodMusicSetTimeMs","FFX_Phyre_StaticDtorNoOp_C97F20","mov ecx,unk_C97F20; jmp nullsub_217; data-xref: Phyre_PArray_bool_PUInt64_RegisterClassDescriptor"),
 ("0xafc340","FFX_Sound_FmodMusicGetLengthMs","FFX_Phyre_StaticDtorNoOp_C986D4","mov ecx,unk_C986D4; call nullsub_12; ret; data-xref: PhyreInit_VertexDecl_InstanceTransform1"),
 ("0xafc3a0","FFX_Sound_FmodMusicGetBeatTimestampMs","FFX_Phyre_StaticDtorNoOp_C985B4","mov ecx,unk_C985B4; call nullsub_12; ret; data-xref: PhyreInit_VertexDecl_ScreenVertex"),
 ("0xafc3f0","FFX_Sound_FmodMusicGetPhase","FFX_Phyre_StaticDtorNoOp_C985F0","mov ecx,unk_C985F0; call nullsub_12; ret; data-xref: PhyreInit_VertexDecl_SkinnableTangent"),
 ("0xafc470","FFX_Sound_FmodMusicGetMusicId","FFX_Phyre_StaticDtorNoOp_C985CC","mov ecx,unk_C985CC; call nullsub_12; ret; data-xref: PhyreInit_VertexDecl_WorldNormal"),
 ("0xafc540","FFX_Sound_FmodMusicGetState","FFX_Phyre_AnnotationStaticDtor_C98B5C","mov ecx,unk_C98B5C; jmp PAnnotation_ListInit(vftable-assign+unlink); data-xref: Phyre_PArray_PVertexStream_Init"),
 ("0xafc5a0","FFX_Sound_FmodMusicIsPlaying","FFX_Phyre_ClassMemberDtor_C989DC","mov ecx,unk_C989DC; jmp PClassDataMember_Destructor; data-xref: Phyre_PGeometry_PVertexStreamArray_ClassDescriptor"),
 ("0xafc600","FFX_Sound_FmodMusicPause","FFX_Phyre_ClassMemberDtor_C98DDC","mov ecx,byte_C98DDC; jmp PClassDataMember_Destructor; data-xref: Phyre_PClassDataMember_InitForGeometryVertexBuffer"),
 ("0xafc650","FFX_Sound_FmodMusicResume","FFX_Phyre_ClassDescDtor_PIndexDataBlockBase","parentCD__55 vftable=PClassDescriptorForType<PGeometry::PIndexDataBlockBase>; jmp Phyre_PClassDescriptor_Destructor"),
 ("0xafc7b0","FFX_Sound_FmodMusicGetNextMusicId","FFX_Phyre_ClassMemberDtor_C99450","mov ecx,byte_C99450; jmp PClassDataMember_Destructor; data-xref: Phyre_Mesh_RegisterClassDescriptor"),
 ("0xafc810","FFX_Sound_FmodMusicGetNextMusicId_0","FFX_Phyre_ClassDescDtor_PMaterialSet","Size__117 vftable=PClassDescriptorForType<PGeometry::PMaterialSet>; jmp Phyre_PClassDescriptor_Destructor"),
 ("0xafc970","FFX_Sound_FmodMusicGetMusicCount","FFX_Phyre_ClassDescDtor_PSkeletonJointBounds","Size__119 vftable=PClassDescriptorForType<PGeometry::PSkeletonJointBounds>; jmp Phyre_PClassDescriptor_Destructor"),
 ("0xafc9d0","FFX_Sound_FmodMusicGetIds","FFX_Phyre_AnnotationStaticDtor_AnnWithValueInt","mov ecx,vtbl_PAnnotationWithValue_Int_10; jmp PAnnotation_ListInit; data-xref: Phyre_StringArray4_ClassDescriptorInit"),
 ("0xafca60","FFX_Sound_FmodMusicGetTempo","FFX_Phyre_ClassDescDtor_PArrayPString4","Size__124 vftable=PClassDescriptorForType<PArray<PString,4>>; jmp Phyre_PClassDescriptor_Destructor"),
 ("0xafcac0","FFX_Sound_FmodMusicFindTrack","FFX_Phyre_ClassMemberDtor_C9A008","mov ecx,byte_C9A008; jmp PClassDataMember_Destructor; data-xref: Phyre_IntArray4_ClassDescriptorInit"),
 ("0xafcbc0","FFX_Sound_FmodMusicGetTrackName","FFX_Phyre_MemberArrayDtor_C99D14","mov ecx,dword_C99D14; jmp PClassDataMemberArray_VftableInit(array dtor); data-xref: PGeometry_PMeshElementGroup_ClassDescriptor"),
 ("0xafccc0","FFX_Sound_FmodMusicGetTrackName_0","FFX_Phyre_ClassMemberDtor_C9A8EC","mov ecx,byte_C9A8EC; jmp PClassDataMember_Destructor; data-xref: Phyre_PGeometry_PMeshElementGroup_ClassDescriptor"),
 ("0xafcec0","FFX_Sound_FmodMusicGetMusicNameFromMusicId","FFX_Phyre_SpotLightSlotDtor","PLightType vftable assign + PLightType_UnlinkNode + clears slot[g_atelFuncspaceCount_3_12]; data-xref: PhyreInit_SpotLight"),
 ("0xafcfe0","FFX_Sound_FmodMusicGetIndexFromMusicId","FFX_Phyre_ClassMemberDtor_C9B0A8","mov ecx,byte_C9B0A8; jmp PClassDataMember_Destructor; data-xref: PLight_RegClass"),
 ("0xafd0b0","FFX_Sound_FmodMusicGetMusicIdFromIndex","FFX_Phyre_StaticListNodeDtor_180","unlink p_linkedList_180 + cond Engine_AlignedFree(ptr_61); data-xref: PLight_RegClass"),
 ("0xafd1f0","FFX_Sound_InitFmodMusic","FFX_Phyre_StaticListNodeDtor_186","unlink p_linkedList_186 + cond Engine_AlignedFree(ptr_66); data-xref: PLight_RegClass"),
 ("0xafd7d0","FFX_Sound_SoundSwUpdate","FFX_Phyre_MemberArrayDtor_C9D2E0","mov ecx,dword_C9D2E0; jmp PClassDataMemberArray_VftableInit(array dtor); data-xref: Phyre_ShaderStreamDefArray_ClassDescriptorInit"),
 ("0xafdc80","FFX_Sound_ProcessSoundCommands","FFX_Phyre_TypeInfoDtor_PSamplerState","typeInfo__48 vftable=PClassDescriptorForType<PRendering::PSamplerState>; jmp Phyre_PClassDescriptor_Destructor; data-xref: PhyreInit_PSamplerState"),
 ("0xafde30","FFX_Sound_FlushSoundCmds","FFX_Phyre_StaticListNodeDtor_193","unlink p_linkedList_193 + cond Engine_AlignedFree(ptr_70); data-xref: PSamplerState_RegClass"),
 ("0xafe300","FFX_Sound_InteractiveMusicUpdate","FFX_Phyre_ClassMemberDtor_CA3620","mov ecx,byte_CA3620; jmp PClassDataMember_Destructor; data-xref: Phyre_PClassDataMember_InitForTexture"),
 ("0xafe440","FFX_Sound_ResolveSoundSource","FFX_Phyre_TypeInfoDtor_PRenderTarget","typeInfo__49 vftable=PClassDescriptorForType<PRendering::PRenderTarget>; jmp Phyre_PClassDescriptor_Destructor; data-xref: PhyreInit_PRenderTarget"),
 ("0xafeca0","FFX_Sound_FadeInMusic","FFX_Phyre_AnnotationStaticDtor_CA5B64","mov ecx,dword_CA5B54+10h; jmp PAnnotation_ListInit; data-xref: Phyre_PArray_PContextVariantFoldingTable_Init"),
 ("0xaff100","FFX_Sound_MusicGetBgmDefine","FFX_Phyre_ClassDescDtor_PArrayPContextSwitch4","Size__164 vftable=PClassDescriptorForType<PArray<PRendering::PContextSwitch const*,4>>; jmp Phyre_PClassDescriptor_Destructor"),
 ("0xaff3d0","FFX_Sound_IsTrackFromSq","FFX_Phyre_StaticListNodeDtor_CA7888","unlink list@CA7888 + cond Engine_AlignedFree(ptr_81); data-xref: Phyre_PMeshInstance_registerFields"),
 ("0xaffa30","FFX_Sound_GetSfxMasterVolume","FFX_Phyre_TypeInfoDtor_PStructuredBuffer","typeInfo__59 vftable=PClassDescriptorForType<PRendering::PStructuredBuffer>; jmp Phyre_PClassDescriptor_Destructor; data-xref: PhyreInit_PStructuredBuffer"),
 ("0xaffaa0","FFX_Sound_GetMusicMasterVolume","FFX_Phyre_TypeInfoDtor_PIndirectArgsBuffer","typeInfo__60 vftable=PClassDescriptorForType<PRendering::PIndirectArgsBuffer>; jmp Phyre_PClassDescriptor_Destructor; data-xref: PhyreInit_PIndirectArgsBuffer"),
 ("0xaffc20","FFX_Sound_SetSfxMasterVolume","FFX_Phyre_StaticListNodeDtor_CA92B8","unlink list@CA92B8 + cond Engine_AlignedFree(ptr_90); data-xref: Phyre_RegisterPSceneNodeDescriptor"),
 ("0xaffc60","FFX_Sound_SetMusicMasterVolume","FFX_Phyre_StaticListNodeDtor_CA9358","unlink list@CA9358 + cond Engine_AlignedFree(ptr_91); data-xref: Phyre_RegisterPSceneNodeDescriptor"),
 ("0xaffd20","FFX_Sound_GetMusicTypeForNotify","FFX_Phyre_StaticListNodeDtor_CA92E0","unlink list@CA92E0 + cond Engine_AlignedFree(ptr_94); data-xref: Phyre_RegisterPSceneNodeDescriptor"),
 ("0xaffdb0","FFX_Sound_SetSystemMute","FFX_Phyre_ClassMemberDtor_CA9548","mov ecx,unk_CA9548; jmp PClassDataMember_Destructor; data-xref: Phyre_RegisterPSceneNodeDescriptor"),
 ("0xb003e0","FFX_Sound_StreamInitialise","FFX_Phyre_TypeInfoDtor_PAnimationClipBinding","typeInfo__64 vftable=PClassDescriptorForType<PAnimation::PAnimationClipBinding>; jmp Phyre_PClassDescriptor_Destructor; data-xref: PhyreInit_PAnimationClipBinding"),
 ("0xb006e0","FFX_Sound_StreamAsyncProc_structural","FFX_Phyre_ClassMemberDtor_CAAAA4","mov ecx,unk_CAAAA4; jmp PClassDataMember_Destructor; data-xref: PhyrePAnimationClip_Initialize"),
 ("0xb015e0","FFX_Sound_StreamRead_structural","FFX_Phyre_StaticListNodeDtor_CADDB8","unlink list@CADDB8 + cond Engine_AlignedFree; data-xref: Phyre_RegisterPAnimatableComponentDescriptor"),
 ("0xb08080","FFX_Sound_SpuVoiceCallback_structural","FFX_Phyre_TypeInfoDtor_PInputSourceTouchPinch","typeInfo__20 vftable=PClassDescriptorForType<PInputs::PInputSourceTouchPinch>; jmp Phyre_PClassDescriptor_Destructor; data-xref: PhyreInit_PInputSourceTouchPinch"),
 # === Get-named setters/clearers ===
 ("0x821f50","FFX_FieldRender_GetWireframeToggle","FFX_FieldRender_ToggleWireframeFlag","al=[12FBB6F]; dec al; and al,1; [12FBB6F]=al — toggles bit0, never returns"),
 ("0x82cc80","FFX_Field_GetShadowMode","FFX_Field_ClearShadowMode","xor eax; mov [1300704],ax; ret — clears word global, no read"),
 ("0x82ccf0","FFX_Field_GetLightingByte","FFX_Field_ClearLightingByte","xor eax; mov [13006F4],ax; ret — clears word global, no read"),
 ("0x826e30","FFX_Chr_GetCurrentBlockIndex","FFX_Chr_ClearCurrentBlockIndex","mov [12FBD54],0; ret — clears index global, no read; callers = Chr scan/fns as reset"),
 ("0x86a150","FFX_SeSep_GetChunkPtr","FFX_SeSep_ClearChunkCtxSlot","imul eax,arg,238h; mov [g_FFX_SeSepChunkCtxTable+eax],0 — clears ctx slot field, no read"),
 ("0x890e10","FFX_Field_GetAnimatedBgVar1","FFX_Field_SetAnimatedBgVar1_const9","mov [133D6B4],9; ret — writes const to word global"),
 ("0x890e20","FFX_Field_GetAnimatedBgVar2","FFX_Field_ClearAnimatedBgVar2","mov [133C8FC],0; ret — clears byte flag; callers EscMenu item draw"),
 ("0x890e30","FFX_Field_GetAnimatedBgVar3","FFX_Field_SetAnimatedBgVar3_const6","mov [133F668],6; ret — writes const; data-xref widget table C64CE8"),
 ("0x890e40","FFX_Field_GetAnimatedBgVar4","FFX_Field_SetAnimatedBgVar4_const7","mov [133D6C8],7; ret — writes const"),
 ("0x890e60","FFX_Field_GetAnimatedBgVar5","FFX_Field_ClearAnimatedBgVar5","mov [133F4D0],0; ret — clears dword; caller Battle_ProcessSceneStateQueue"),
 ("0x890e70","FFX_Field_GetAnimatedBgVar6","FFX_Field_SetAnimatedBgVar6_const9","mov [133D6F4],9; ret — writes const"),
 ("0x890e80","FFX_Field_GetAnimatedBgStruct","FFX_Field_AnimatedBgWidgetCallback","calls WidgetFindAndActivate('bwakk',2)+FieldMenuFreeStrings+clears 133C8FF — debug-menu widget callback, not getter"),
 ("0x8d0400","FFX_CustomizeMenu_GetCurrentSlotCharId","FFX_CustomizeMenu_ComputeCurrentSlotCharId","derives id via [186A5DC]+48 -> word table 1597730 -> caches 186A5F0 (0xFF if 0); stores, never returns"),
 ("0xaf0e00","FFX_Sound_GetDefaultFmodChannelgroup","FFX_Sound_ClearDword_22FB534","mov [22FB534],0; ret — clears BSS dword, no read, 0 xrefs"),
 ("0x887df0","FFX_RenderEngine_GetSetFrameCount","FFX_RenderEngine_SetFrameCount","[13301B0]=mode; eax=[13301B0]; ret — pure setter w/ readback, no get path"),
 ("0x824ec0","FFX_Chr_GetModelFloat_12FBC10","FFX_Chr_WriteModelFloatTriple_12FBBFC","fstp arg0->12FBFFC, arg4->12FC00, arg8->12FC04 — stores 3 floats; callers: setWindParams/PhysicsSettingsUI/ListCommand"),
 ("0x8be3c0","FFX_MenuPad_ReadTriggerEdge_D","FFX_MenuPad_XorScreenIdHighWord","eax=[g_FFX_CurrentMenuScreenId]; xor arg; and FFFF0000; stores back — updates screen id high word, not a pad read"),
 # === Save_File cluster ===
 ("0x8b34a0","FFX_Save_FileExists","FFX_Save_RefreshSlotCountCache","call Save_GetSlotCount; [n0x2000_1]=eax; ret — caches slot count, no existence check"),
 ("0x8b3530","FFX_Save_FileOpen","FFX_Save_MenuOpenInit","SetFileHandle(1)+zero state+BlockAlloc+SetCurrentScreenId(0)+KeyRepeatCheck(-16) — save-menu open/init, no file open"),
 ("0x8b35c0","FFX_Save_FileRead","FFX_Save_ClearStagingBuffer400","call FileWrite(returns buf ptr 159E428); memset(ptr,0,400h) — zeroes staging buffer, no read"),
 ("0x8b35e0","FFX_Save_FileWrite","FFX_Save_GetStagingBufferPtr","mov eax,offset unk_159E428; ret — returns buffer ptr, no write"),
 ("0x8b3630","FFX_Save_FileSeek","FFX_Save_InitBufferTableLoop_structural","loop: TextLookupByTable3(2000h+i)+BufferCountByType+BufferWriteFlags — builds save buffer table, no seek"),
 # === thunk-named-as-impl / wrong-side ===
 ("0x8ab270","FFX_Menu_KeyRepeatTrigger","FFX_Menu_CheckFlagId_thunk","pure trampoline -> FFX_Battle_CheckFlagId (bit test on word table 1130F1C, id<0x80); callers SphereGrid item code"),
 ("0x88d130","FFX_Mscd_GetWalkStructFuncPtr2","FFX_Mscd_InvokeWalkStructFunc8","call GetWalkStructSkyDataPtr(cd_read); mov eax,[eax+8]; jmp eax — INVOKES func-ptr slot +8, doesn't return it"),
 ("0x8cc2d0","FFX_SphereGrid_ActivateLockSlot","FFX_SphereGrid_DeactivateLockSlot","if cnt186A5BC>1: DismissCurrentPopup; jmp FreeActiveNode(marks node flag+clears active ptr) — teardown, not activate; data-xref cb table C5A730"),
 ("0x8ba360","FFX_FieldMenu_MenuSceneTick","FFX_SaveRam_AddGil","neg arg; jmp SaveRam_SpendGil -> gil-(-arg)=+arg — ADDS gil (refund/gain); caller FieldMenu_DrawItemIcon"),
 ("0x897660","FFX_EscMenu_HelperFontMetric","FFX_BtlUI_GetActorDataFloatPtr_thunk","pure trampoline -> FFX_BtlUI_GetActorDataFloatPtr (actor float/battle data by idx); callers EscMenu panel draws"),
 ("0x76edf0","FFX_Field_ResetTransitionFlagAndNotify","FFX_Video_StopMovieAndResetFlags","if gMoviePicture: gMoviePlay=0,gMovieDrawChr=1,gMoviePicture=0; jmp Video_StopMovieIfActive — movie teardown for scene reload"),
 ("0x8c1370","FFX_Menu_DrawCommand","FFX_Menu2D_SetClipRectCoord_thunk_A","pure trampoline -> Menu2D_SetClipRectCoord (writes clip floats 1871690..C4); callers draw code expecting clip-rect"),
 ("0x8dd440","FFX_Menu_DrawRect","FFX_Menu2D_SetClipRectCoord_thunk_B","pure trampoline -> Menu2D_SetClipRectCoord; callers DrawClippedWindow/DrawFullScreenRect"),
 ("0x8f2f70","FFX_Save_SpawnAndInitSaveLoadMenus","FFX_Save_ReturnArg0_stub","mov eax,[arg0]; ret — passthrough stub, spawns nothing"),
 ("0x879dd0","FFX_Mem_RamSaveSerialize","FFX_Dbg_SceWriteWrapper_thunk","pure trampoline -> FFX_Dbg_SceWriteWrapper (dbgPrintf 'Virtuos sceWrite' stub, returns 0); callers Atel_SaveRamToFile"),
 ("0x879de0","FFX_Mem_RamLoadDeserialize","FFX_FileIO_PFileStream_SeekSafe_thunk","pure trampoline -> FFX_File_SeekWrapper -> FileIO_PFileStream_SeekSafe — a seek, not deserialize"),
 ("0x7e4d50","FFX_Magic_AllocTextureSlot_structural","FFX_Magic_FreeTextureSlotsByMask","loop slots 11A04A0..11A05A0: if(slot&mask) slot=0 — frees by bitmask, never allocs; callers ParticleEffectFree/FreeAllEffects"),
 ("0x7ff800","FFX_Magic_AllocTextureSlot_structural_w","FFX_Magic_FreeAllTextureSlots","push -1; call FreeTextureSlotsByMask — frees ALL slots; callers Battle_ServiceTick/UpdateSceneNodeTransitions/UnbindActorNode"),
 ("0x86a140","FFX_Atel_UnbindActorNode","FFX_Atel_FreeAllTextureSlots_thunk","pure trampoline -> FreeAllTextureSlots — frees all texture slots, no actor-node touch"),
 ("0x8be0a0","FFX_MenuPad_ReadAllHeld","FFX_FieldMenu_DrawConfigWeaponWindow","reads TkBtlEndWeapon word table, scales 1080->416/1920->512 coords, calls Menu_DrawWindow — draws config weapon panel; only caller FieldMenu_DrawConfigPanel"),
 ("0x759740","FFX_FieldMap_CheckAndRenderObject","FFX_Phyre_MemberCb_PpvPortrait_structural","data-xrefs only (4 descriptor records C3B390/C3CA38/C3EED0/C64CE8): resolves ppvMng object + member-offset table + calls HudParty_SetPortrait — Phyre member callback, not render"),
]

with open("work/_mislabel_audit/rename_plan.json","w") as fh:
    json.dump([{"addr":a,"old":o,"new":n,"evidence":e} for a,o,n,e in PLAN], fh, indent=1)
print(len(PLAN), "planned renames")
