<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>PsarcRepairFfx2</AssemblyName>
    <RootNamespace>PsarcRepairFfx2</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="PsarcWriter.cs" />
    <Compile Include="_psarc_repair_ffx2.cs" />
  </ItemGroup>
</Project>
